<?php

    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<h1>Manage product interactivity</h1>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    
    <?php // List mode ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
            <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
      
            <?php // Product id   ?>
            <?php   $product_id=$_product->getId();//product id
		

            $chk_enable = '';
            $product_id=$_product->getId();

            $connection = Mage::getSingleton('core/resource')->getConnection('finware_index');
            $result = $connection->fetchAll("SELECT active FROM finware_index where product_id = $product_id");

            $chk_enable = $result[0]['active'];
            if ($chk_enable == 'Yes')
            {
            ?>
                <?php // Product Image ?><?php //echo $this->getUrl("edit/admin/page")."?id=$product_id"  ?>
                <a href="<?php echo $_product->getProductUrl(); ?>" target="_blank" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <?php // Product Name ?>
                <div class="product-shop">
                    <div class="f-fix">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name" style="margin-top: 8%;margin-left: 30%"><a href="<?php echo $_product->getProductUrl(); ?>" target="_blank" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                        <a id="<?php echo  $product_id; ?>" class="disable" href='#' title="Disable" style="margin-left: 55%;display: inline"   >Disable/</a>
                        &nbsp<a id="edit" href="<?php echo $this->getUrl("edit/admin/page")."?id=$product_id"  ?>" title="Edit" style="display: inline" >Edit</a>
                        <a  id="disabled" href="<?php echo $this->getUrl("edit/admin/page")."?id=$product_id"  ?>" title="Enable" style="margin-left: 55%;display: none">Enable</a>
                        <?php         
             
            }
            else if($chk_enable == 'No')
            {
                ?>

                        <?php // Product Image ?>
                        <a href="<?php echo $_product->getProductUrl(); ?>" target="_blank" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <?php // Product Name ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name" style="margin-top: 8%;margin-left: 30%"><a href="<?php echo $_product->getProductUrl(); ?>" target="_blank" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                                <a  id="disabled" href="<?php echo $this->getUrl("edit/admin/page")."?id=$product_id"  ?>" title="Disabled" style="margin-left: 55%;">Enable</a>
                <?php
            }
            else
            {
                ?>
        
                <?php // Product Image ?>
                <a href="<?php echo $_product->getProductUrl(); ?>" target="_blank" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <?php // Product Name ?>
                <div class="product-shop">
                    <div class="f-fix">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name" style="margin-top: 8%;margin-left: 30%"><a href="<?php echo $_product->getProductUrl(); ?>" target="_blank" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                        <a id="enable" href="<?php echo $this->getUrl("add/admin/page")."?id=$product_id" ?>" title="Enable" style="margin-left: 55%;">Enable</a>
                <?php
            }
                ?>             

                        </h2>
                    </div>
                </div>
                <div>
                </div>
                </li>
        <?php endforeach; ?>
        </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
 <!-- <script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'skin/js/web/web.js'?>" type="text/javascript"></script> -->
 

   
    </div>
<?php endif; ?>

<script type="text/javascript">
 //Disable Product
;(function($){
    $(document).ready(function(){
        $(".disable").click(function(){
            var r = confirm("Do you want to disable?");
            if (r == true) 
            {
                product_id = this.id;
                document.getElementById("edit").style.display = "none";
                document.getElementById(""+product_id).style.display = "none";
                document.getElementById("disabled").style.display = "inline";
             
                $.ajax({
                    type: 'GET',   
                    url: '<?php echo $this->getUrl("web/admin/disable");?>?id='+product_id,
                    success: function(htmli)
                    {
                        console.log(htmli);
                    }
                });
            }
        });
    });
})(jQuery);
    



</script>
